### ISSUE TITLE
403: quotaExceeded

### ISSUE THREAD

**Issue by betterthanever2** [dunkyl/SlyPyYTDAPI#2]
After working with the lib for some time, at some point I started getting `quotaExceeded` error. I don't remember ever getting such error when working with non-async YT clients. Here's full error message:

```
ApiError('''
Status: 403
Reason: {
  "error": {
    "code": 403,
    "message": "The request cannot be completed because you have exceeded your \\u003ca href=\\"/youtube/v3/getting-started#quota\\"\\u003equota\\u003c/a\\u003e.",
    "errors": [
      {
        "message": "The request cannot be completed because you have exceeded your \\u003ca href=\\"/youtube/v3/getting-started#quota\\"\\u003equota\\u003c/a\\u003e.",
        "domain": "youtube.quota",
        "reason": "quotaExceeded"
      }
    ]
  }
}
''')
```

Like I said, I have never seen this exception before, even though my interactions with YT API could be relatively heavy. Why does this occur, and how do I deal with it?

**Comment by dunkyl** [comment]
You can view your quota on your project the Google Cloud Console, under APIs & Services, YouTube, then the Quotas and System Limits tab. I think there is sometimes a long-term limit (maybe, per month?) and always a short term limit (per minute or second). Then, you'll get to see exact numbers for what you can and can't do.

If you are using limit=None on paginated a request (such as `search_videos`), and using all the results from it, it could be making lots of requests quickly. For example, if there were 10,000 video results, that could be at least 200 requests.

One solution to still go through many requests, just slower to make the quota happy, could be to use the async generator with a delay:
```py
MAX_REQUESTS_PER_SECOND = 5
async for video in yt.search_videos("example", limit=None):
    asyncio.sleep(1/MAX_REQUESTS_PER_SECOND)
    ...
```
This would not account for any multiple clients or for parallel queries, though, if that might also be contributing.

**Comment by dunkyl** [comment]
Oh! And it seems there are changes to the quota cost of searching since I last looked: ["A call to this method has a quota cost of 100 units."](https://developers.google.com/youtube/v3/docs/search/list)
This may be a bigger reason for it.

**Comment by betterthanever2** [comment]
> Oh! And it seems there are changes to the quota cost of searching since I last looked: ["A call to this method has a quota cost of 100 units."](https://developers.google.com/youtube/v3/docs/search/list) This may be a bigger reason for it.

Well, this sucks. Is there another method to fetch vids of a particular channel after a particular date?

**Comment by dunkyl** [comment]
Not that I am aware of, no. You can request an increased quota from Google. I've had mixed success with that, and sometimes they will increase it for you without asking too if it gets used consistently.
Also, it seems plausible that the quota cost of 100 includes all the 'pages' of a search. I am not certain.

**Comment by dunkyl** [comment]
Any chance you wanting to make a bot that does an action when a new video is posted?
If you want to poll for new videos from a particular channel regularly, perhaps RSS is the way to go.
YouTube publishes RSS feeds at `https://www.youtube.com/feeds/videos.xml?channel_id=<channel_id>`

**Comment by betterthanever2** [comment]
> Any chance you wanting to make a bot that does an action when a new video is posted? If you want to poll for new videos from a particular channel regularly, perhaps RSS is the way to go. YouTube publishes RSS feeds at `https://www.youtube.com/feeds/videos.xml?channel_id=<channel_id>`

RSS is very interesting idea, it hasn't occurred to me. Thank you, I'll look into it. In the meantime, I'm gonna close this ticket since there is nothing to be done about it.
