### ISSUE TITLE
Values are missing in the response

### ISSUE THREAD

**Issue by betterthanever2** [dunkyl/SlyPyYTDAPI#5]
Hi. Below is an example of response I get via `sly`. 

(Take into account, that this is currently my fork, which may differ slightly in data structure. However, the point of issue here is fetching values of certain fields, which I didn't temper with)

I then tried to fetch this video via the `pyyoutube` library. Some of the values that were `null` with Sly, did give me some data. These have this thing `<----------<<<` and square brackets next to them with value I received.
```
{
   "allowed_in": null,
   "blocked_in": null,
   "caption": null,  <----------<<< [false]
   "channel_id": "UCZ_w8UzwFVoWIX1qgHLaCaw",
   "channel_name": "Ваши Новости",
   "comment_count": null,<----------<<< [5]
   "default_audio_language": "ru",
   "definition": null,<----------<<< [hd]
   "description": "",
   "dimension": null,<----------<<< [2d]
   "duration": null, <----------<<< [PT15S]
   "failure_reason": null,
   "favourite_count": null,
   "has_viewable_stats": null,
   "id": "LO0uDf8yqxg",
   "is_embeddable": null,
   "is_licensed": null,<----------<<< [false]
   "is_livestream": false,
   "is_made_for_kids": null,
   "license": null,
   "like_count": null,<----------<<< [108]
   "livestream_details": null,
   "localizations": null,
   "localized_description": "",
   "localized_title": "Поддубный: Очень хотелось жить!",
   "privacy": null,
   "projection": null,<----------<<< [rectangular]
   "published_at": "2024-08-11T13:49:46",
   "recording_date": null,
   "rejection_reason": null,
   "self_declared_made_for_kids": null,
   "tags": [],
   "thumbnails": [
      "https://i.ytimg.com/vi/LO0uDf8yqxg/default.jpg",
      "https://i.ytimg.com/vi/LO0uDf8yqxg/mqdefault.jpg",
      "https://i.ytimg.com/vi/LO0uDf8yqxg/hqdefault.jpg",
      "https://i.ytimg.com/vi/LO0uDf8yqxg/sddefault.jpg",
      "https://i.ytimg.com/vi/LO0uDf8yqxg/maxresdefault.jpg"
   ],
   "title": "Поддубный: Очень хотелось жить!",
   "topic_categories": null,<----------<<< [['https://en.wikipedia.org/wiki/Society', 'https://en.wikipedia.org/wiki/Television_program']]
   "upload_status": null,
   "view_count": null<----------<<< [2313]
}
```

**Comment by dunkyl** [comment]
By default, this library only asks for the snippet part of a video, to have the basics with minimal quota cost. In some cases, the snippet is the only part you are allowed to ask for in a single request.

To get every field, you would need to pass the set `parts={Part.DETAILS, Part.SNIPPET, Part.STATUS, Part.STATISTICS, etc ... }` to the request. The newly uploaded v0.4.0 has `Part.ALL_PUBLIC` as a convenient way to request most parts.

**Comment by betterthanever2** [comment]
Ok, but `duration`, among others, comes from `snippet`

**Comment by betterthanever2** [comment]
oh no, sorry, it comes from `contentDetails`. Still, seems like a thing most people would appreciate

**Comment by betterthanever2** [comment]
> The newly uploaded v0.4.0 has Part.ALL_PUBLIC as a convenient way to request most parts.

@dunkyl can you please give me a complete example of making request with `Part.ALL_PUBLIC`?

**Comment by dunkyl** [comment]
I messed up my implementation of ALL_PUBLIC, at least on some Python versions, and deployed a hotfix v0.4.2. It is a now static method.

```py
import asyncio
from SlyYTDAPI import *

async def main():
    yt = YouTubeData(open('api_key.txt').read())

    my_video = await yt.video('dQw4w9WgXcQ', parts=Part.ALL_PUBLIC())
    print(F"The video is {my_video.duration} seconds long")
    
asyncio.run(main())
```

**Comment by betterthanever2** [comment]
Seems like this can be closed
