### ISSUE TITLE
Unknown duration format

### ISSUE THREAD

**Issue by betterthanever2** [dunkyl/SlyPyYTDAPI#8]
When updating my db, I'm getting a number of exceptions related to duration, for example `Error fetching updates from channel UCVPYbobPRzz0SjinWekjUBw: Unknown duration format: PT21M`. Here are formats that were deemed 'uknown':

- PT1M
- PT1H8M
- PT21M
- PT46M
- PT44M

**Comment by dunkyl** [comment]
Ah, TIL that the seconds field is sometimes omitted. A fix for this will be included in the next version.

**Comment by betterthanever2** [comment]
@dunkyl I'm getting one more bad format after the update: `P0D`. Not even sure what this is supposed to be, yet I'm getting it.

**Comment by dunkyl** [comment]
Can you share the video?

**Comment by betterthanever2** [comment]
Most likely, it was this video: https://www.youtube.com/watch?v=a4jIQsmRjY8
In case you can read russian, I apologize for ru propaganda, it's just the subject of my research.

**Comment by dunkyl** [comment]
No problem, understandable. It is interesting, and this also made me realize I never handled hidden counts!

**Comment by dunkyl** [comment]
A new version is up.
I will leave the issue open for a bit, since I don't have a complete understanding of when or why videos might have durations like this.

**Comment by betterthanever2** [comment]
> A new version is up. I will leave the issue open for a bit, since I don't have a complete understanding of when or why videos might have durations like this.

Yeah, it is weird. Possibly, a scheduled stream?

**Comment by dunkyl** [comment]
Indeed after some testing, scheduled streams and streams that have been up for only moments do this, which makes sense.
